### PR TITLE
Release `1.17.0`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `1.17.0` release.
Here you can find all related translations changes: [1.16.0...main](https://github.com/flarum-lang/turkish/compare/1.16.0...main).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should **[approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request)** this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release. You can read more about the process on [forum](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76).

<details>
<summary>Show release notes preview</summary>

## 1.17.0

**Genel değişiklikler**:

* Flarum çekirdek çevirileri güncellendi.

**Yeni uzantılar için destek eklendi**:

* [`flarum/bbcode`](https://github.com/flarum/bbcode)
* [`gbcl/userip`](https://github.com/GBCLStudio/userip)
* [`marchccc/flarum-ext-mentions-group-users`](https://github.com/Marchccc/flarum-ext-mentions-group-users)
* [`xsoft-ict/mason-tag`](https://github.com/xsoft-ict/fof-mason-tag)

**Uzantılar için çeviriler güncellendi**:

* [`acpl/flarum-lscache`](https://github.com/android-com-pl/flarum-lscache)
* [`antoinefr/flarum-ext-money`](https://github.com/AntoineFr/flarum-ext-money)
* [`askvortsov/flarum-pwa`](https://github.com/askvortsov1/flarum-pwa)
* [`clarkwinkelmann/flarum-ext-mailing`](https://github.com/clarkwinkelmann/flarum-ext-mailing)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/sticky`](https://github.com/flarum/sticky)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/links`](https://github.com/FriendsOfFlarum/links)
* [`fof/polls`](https://github.com/FriendsOfFlarum/polls)

Tüm değişiklikler: [1.16.0...1.17.0](https://github.com/flarum-lang/turkish/compare/1.16.0...1.17.0).

</details>

### CODE REVIEW

**Comment by selmanozturk** [comment]
Hi @tolgaaaltas ✋ Waiting for your review...

**Comment by tolgaaaltas** [comment]
Hi Selman, I’m in the military right now. I’ll check asap.07.07.2023, 22:00, "Selman" ***@***.***>:
Hi @tolgaaaltas ✋ Waiting for your review...

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Saygılarımla, Tolga ALTAŞhttps://tolgaaltas.com+90 542 577 56 ***@***.*** Regards, Tolga ALTAŞhttps://tolgaaltas.com+90 542 577 56 ***@***.***

**Comment by rob006** [comment]
@tolgaaaltas FYI: I have granted @selmanozturk maintainer permissions in this repository, he will be able to tag new releases until you end your military service. Then you can decide whether you want to maintain language pack solo, or work together with  @selmanozturk.

see https://discuss.flarum.org/d/27519-the-flarum-language-project/235

**Review by selmanozturk — APPROVED** [review]

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## Sürüm [`1.17.0`](https://github.com/flarum-lang/turkish/releases/tag/1.17.0)

**Genel değişiklikler**:

* Flarum çekirdek çevirileri güncellendi.


**Yeni uzantılar için destek eklendi**:

* [`flarum/bbcode`](https://github.com/flarum/bbcode)
* [`gbcl/userip`](https://github.com/GBCLStudio/userip)
* [`marchccc/flarum-ext-mentions-group-users`](https://github.com/Marchccc/flarum-ext-mentions-group-users)
* [`xsoft-ict/mason-tag`](https://github.com/xsoft-ict/fof-mason-tag)


**Uzantılar için çeviriler güncellendi**:

* [`acpl/flarum-lscache`](https://github.com/android-com-pl/flarum-lscache)
* [`antoinefr/flarum-ext-money`](https://github.com/AntoineFr/flarum-ext-money)
* [`askvortsov/flarum-pwa`](https://github.com/askvortsov1/flarum-pwa)
* [`clarkwinkelmann/flarum-ext-mailing`](https://github.com/clarkwinkelmann/flarum-ext-mailing)
* [`flarum/likes`](https://github.com/flarum/likes)
* [`flarum/mentions`](https://github.com/flarum/mentions)
* [`flarum/sticky`](https://github.com/flarum/sticky)
* [`fof/byobu`](https://github.com/FriendsOfFlarum/byobu)
* [`fof/links`](https://github.com/FriendsOfFlarum/links)
* [`fof/polls`](https://github.com/FriendsOfFlarum/polls)


Tüm değişiklikler: [1.16.0...1.17.0](https://github.com/flarum-lang/turkish/compare/1.16.0...1.17.0).

Güncellemek için şu komutları çalıştırın:

```console
composer update flarum-lang/turkish
php flarum cache:clear
```

~~~

**Pull request merged**
